version: '{branch}-{build}'

build:
  project: Unity-Technologies-networking/Networking.sln
  verbosity: minimal
  
artifacts:
  - path: Unity-Technologies-networking/Output/**/*

image: Visual Studio 2017

