version: '{branch}-{build}'

before_build:
  - nuget restore Unity-Technologies-networking/Networking.sln

build:
  project: Unity-Technologies-networking/Networking.sln
  verbosity: minimal
  
artifacts:
  - path: Unity-Technologies-networking/Output/**/*

image: Visual Studio 2017

