version: '{branch}-{build}'

before_build:
  - nuget restore Mirror/Networking.sln

build:
  project: Mirror/Networking.sln
  verbosity: minimal
  
artifacts:
  - path: Mirror/Output
    name: Mirror

image: Visual Studio 2017

test_script:
  - Mirror\packages\OpenCover.4.6.519\tools\OpenCover.Console.exe -returntargetcode -register:user -target:"nunit3-console.exe" -targetargs:"Mirror\Tests\bin\Debug\Mirror.Tests.dll" -output:"coverage.xml" -filter:"+[Mirror*]* -[Mirror.Tests*]* "

after_test:
  - ps: |
      $env:PATH = 'C:\msys64\usr\bin;' + $env:PATH
      Invoke-WebRequest -Uri 'https://codecov.io/bash' -OutFile codecov.sh
      bash codecov.sh -f "coverage.xml" 

deploy:
  description: 'Mirror $(APPVEYOR_REPO_BRANCH) '
  provider: GitHub
  auth_token:
    secure: G42snf8s5fEos7UfoRSW6eW+8rqGGMH3iw1ZCjRUjcUSKupHUfrKJMXQ11wbjRuW # your encrypted token from GitHub
  artifact: Mirror\Mirror.zip            # upload all NuGet packages to release assets
  draft: false
  prerelease: false
  on:
    appveyor_repo_tag: true        # deploy on tag push only
