name: UPM

on:
  push:
    branches: master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Push UPM package
      run: |
        git subtree push --prefix=Assets/Mirror origin upm
